esphome:
  name: "i2c-velleman-k8000"
  # ... other config


esp8266:
  board: d1_mini


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "NlFzUPWMBcFYDu4T1VYEBAOviYG5FWCEy0fPiwV1G5k="

ota:
  - platform: esphome
    password: "2d8f6ef2a687d20396f71b97aca4f4bb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "I2C-Test Fallback Hotspot"
    password: "Beek56&opa"

captive_portal:

# Example for standard ESP32 (SDA: 21, SCL: 22)
i2c:
  sda: GPIO 4
  scl: GPIO 5
  scan: true  # <--- This triggers the scanner
  id: bus_a 

external_components:
  - source:
      type: local
      path: components
  - source:
      type: local
      path: my_components    


# Example configuration entry
pcf8574:
  - id: 'pcf_uit'
    address: 0x3A
    pcf8575: False

  - id: 'pcf_in'
    address: 0x3B
    pcf8575: False    

tda8444:
  id: dac_chip
  address: 0x21     

web_server:
  port: 80 


# Individual outputs
switch:
  - platform: gpio
    name: "K8000 Uitgang 1"
    pin: { pcf8574: pcf_uit, number: 0, mode: OUTPUT }
    inverted: true
  - platform: gpio
    name: "K8000 Uitgang 2"
    pin: { pcf8574: pcf_uit, number: 1, mode: OUTPUT }
    inverted: true
  - platform: gpio
    name: "K8000 Uitgang 3"
    pin: { pcf8574: pcf_uit, number: 2, mode: OUTPUT }
    inverted: true
  - platform: gpio
    name: "K8000 Uitgang 4"
    pin: { pcf8574: pcf_uit, number: 3, mode: OUTPUT }
    inverted: true
  - platform: gpio
    name: "K8000 Uitgang 5"
    pin: { pcf8574: pcf_uit, number: 4, mode: OUTPUT }
    inverted: true
  - platform: gpio
    name: "K8000 Uitgang 6"
    pin: { pcf8574: pcf_uit, number: 5, mode: OUTPUT }
    inverted: true
  - platform: gpio
    name: "K8000 Uitgang 7"
    pin: { pcf8574: pcf_uit, number: 6, mode: OUTPUT }
    inverted: true
  - platform: gpio
    name: "K8000 Uitgang 8"
    pin: { pcf8574: pcf_uit, number: 7, mode: OUTPUT }
    inverted: true

# 3. De 8 Digitale Ingangen (0x3B)
binary_sensor:
  - platform: gpio
    name: "K8000 Ingang 1"
    pin: { pcf8574: pcf_in, number: 0, mode: INPUT, inverted: true }
  - platform: gpio
    name: "K8000 Ingang 2"
    pin: { pcf8574: pcf_in, number: 1, mode: INPUT, inverted: true }
  - platform: gpio
    name: "K8000 Ingang 3"
    pin: { pcf8574: pcf_in, number: 2, mode: INPUT, inverted: true }
  - platform: gpio
    name: "K8000 Ingang 4"
    pin: { pcf8574: pcf_in, number: 3, mode: INPUT, inverted: true }
  - platform: gpio
    name: "K8000 Ingang 5"
    pin: { pcf8574: pcf_in, number: 4, mode: INPUT, inverted: true }
  - platform: gpio
    name: "K8000 Ingang 6"
    pin: { pcf8574: pcf_in, number: 5, mode: INPUT, inverted: true }
  - platform: gpio
    name: "K8000 Ingang 7"
    pin: { pcf8574: pcf_in, number: 6, mode: INPUT, inverted: true }
  - platform: gpio
    name: "K8000 Ingang 8"
    pin: { pcf8574: pcf_in, number: 7, mode: INPUT, inverted: true }

sensor:
  - platform: pcf8591_custom
    ain0:
      name: "LDR Lichtsterkte"
      filters:
        - lambda: return x * (5.0 / 255.0); # Hier is je lambda weer terug!
    ain1:
      name: "NTC Temperatuur"
    ain2:
      name: "Potentiometer"
    ain3:
      name: "Vrij kanaal"
    update_interval: 5s

number:
  - platform: template
    name: "TDA8444 Kanaal 0"
    min_value: 0
    max_value: 63
    step: 1
    initial_value: 0
    set_action:
      then:
        - lambda: 'id(dac_chip).set_channel_value(0, (uint8_t)x);'

  - platform: template
    name: "TDA8444 Kanaal 1"
    min_value: 0
    max_value: 63
    step: 1
    set_action:
      then:
        - lambda: 'id(dac_chip).set_channel_value(1, (uint8_t)x);'
  
  - platform: template
    name: "TDA8444 Kanaal 2"
    min_value: 0
    max_value: 63
    step: 1
    set_action:
      then:
        - lambda: 'id(dac_chip).set_channel_value(1, (uint8_t)x);'

  - platform: template
    name: "TDA8444 Kanaal 3"
    min_value: 0
    max_value: 63
    step: 1
    initial_value: 0
    set_action:
      then:
        - lambda: 'id(dac_chip).set_channel_value(0, (uint8_t)x);'

  - platform: template
    name: "TDA8444 Kanaal 4"
    min_value: 0
    max_value: 63
    step: 1
    set_action:
      then:
        - lambda: 'id(dac_chip).set_channel_value(1, (uint8_t)x);'
  
  - platform: template
    name: "TDA8444 Kanaal 5"
    min_value: 0
    max_value: 63
    step: 1
    set_action:
      then:
        - lambda: 'id(dac_chip).set_channel_value(1, (uint8_t)x);'

  - platform: template
    name: "TDA8444 Kanaal 6"
    min_value: 0
    max_value: 63
    step: 1
    set_action:
      then:
        - lambda: 'id(dac_chip).set_channel_value(1, (uint8_t)x);'
  
  - platform: template
    name: "TDA8444 Kanaal 7"
    min_value: 0
    max_value: 63
    step: 1
    set_action:
      then:
        - lambda: 'id(dac_chip).set_channel_value(1, (uint8_t)x);'